version: '3'

services:

  mongo:
    container_name: products-kt_mongo
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: products
    ports:
      - 27017:27017
    volumes:
       - ./docker/mongo/initdb:/docker-entrypoint-initdb.d:ro
