
name: 'check'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - code/**

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Build (skipping test)
        working-directory: code
        run: gradle build -x test
        env:
          # disable default JVM in container
          JAVA_HOME:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Build & Test
        working-directory: code
        run: gradle build
        env:
          # disable default JVM in container
          JAVA_HOME: