
name: 'check'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Ignore default JVM
        run: JAVA_HOME=""

      - name: Check default JVM
        run: echo $JAVA_HOME

      - name: Build (skipping test)
        working-directory: code
        run: gradle build -x test --info
